--- 
clone: 
  depth: 1
kind: pipeline
name: Build Clang
steps: 
  - 
    commands: 
      - "git clone https://github.com/bagus02/clang-build"
      - "cd clang-build"
      - "bash build-toolchain.sh"
      - "bash upload-build.sh"
    environment: 
      TG_TOKEN: 
        from_secret: TG_TOKEN
      GH_TOKEN:
        from_secret: GH_TOKEN
      GH_USER:
        from_secret: GH_USER
      GH_REL_REPO:
        from_secret: GH_REL_REPO
      GIT_AUTHOR_NAME:
        from_secret: GIT_AUTHOR_NAME
      GIT_AUTHOR_EMAIL:
        from_secret: GIT_AUTHOR_EMAIL
      TG_CHAT_ID:
        from_secret: TG_CHAT_ID
    image: gengkapak/llvm
    name: Build
    trigger: 
      branch: 
        - master
